# Generated by Django 5.0.14 on 2026-03-11 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_companychatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companychatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companychatmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companychatmessage',
            name='deleted_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CompanyChatMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='chat.companychatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_message_reads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='companychatmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='company_read_messages', through='chat.CompanyChatMessageRead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='companychatmessage',
            index=models.Index(fields=['created_at'], name='chat_compan_created_d0022e_idx'),
        ),
        migrations.AddIndex(
            model_name='companychatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='chat_compan_sender__db337f_idx'),
        ),
        migrations.AddIndex(
            model_name='companychatmessageread',
            index=models.Index(fields=['message', 'read_at'], name='chat_compan_message_c34495_idx'),
        ),
        migrations.AddIndex(
            model_name='companychatmessageread',
            index=models.Index(fields=['user', 'read_at'], name='chat_compan_user_id_0a46d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companychatmessageread',
            unique_together={('message', 'user')},
        ),
    ]
