# Generated by Django 5.0.14 on 2026-05-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_add_message_features'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companychatmessage',
            name='chat_compan_is_pinn_idx',
        ),
        migrations.RenameIndex(
            model_name='companychatmessagereaction',
            new_name='chat_compan_message_23d99e_idx',
            old_name='chat_compan_message_react_idx',
        ),
        migrations.RemoveField(
            model_name='companychatmessage',
            name='attachment_size',
        ),
        migrations.RemoveField(
            model_name='companychatmessage',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='companychatmessage',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='companychatmessage',
            name='pinned_at',
        ),
        migrations.RemoveField(
            model_name='companychatmessage',
            name='pinned_by',
        ),
        migrations.RemoveField(
            model_name='companychatmessage',
            name='updated_at',
        ),
    ]
