# Generated by Django 5.0.14 on 2026-05-11 09:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_companychatmessage_chat_compan_is_pinn_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companychatmessagereaction',
            unique_together={('message', 'user')},
        ),
    ]
