# Generated by Django 5.0.14 on 2026-03-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('leave_request', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_balance_adjusted', 'Leave Balance Adjusted'), ('employee_added', 'Employee Added'), ('salary_paid', 'Salary Paid'), ('profile_updated', 'Profile Updated')], db_index=True, max_length=30),
        ),
    ]
