# Generated by Django 5.0.14 on 2026-05-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_profile_picture'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='salary_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='salary_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(fields=('employee', 'salary_month', 'salary_year'), name='unique_employee_payroll_period'),
        ),
    ]
